# https://www.mkdocs.org/user-guide/writing-your-docs/
site_name: gricean-pragmatics
site_url: "https://clap-purdue.github.io/gricean-pragmatics/"
site_description: Project documentation with Markdown.
site_author: Elsayed Issa

repo_url: https://github.com/clap-purdue/gricean-pragmatics
edit_uri: "blob/main/docs/"

theme:
  name: readthedocs
  locale: en
  highlightjs: true
  hljs_style: github
  hljs_languages:
    - yaml

nav:
  - Home: index.md
  - Installation: installation.md
  - Documentation: documentation.md
  - Tutorials: tutorial.md
  - API: api.md
  - Contribution: contribution.md


copyright: Copyright &copy; 2024 <a href="https://github.com/clap-purdue">Computational Linguistics @ Purdue </a>, Maintained by the <a href="/about/release-notes/#maintenance-team">MkDocs Team</a>.